

apiVersion: v1
kind: Service
metadata:
  name: springboot-sample-service
  namespace: demo
spec:
  sessionAffinity: ClientIP
  selector:
    app: springboot-sample
  ports:
  - protocol: TCP
    nodePort: 32001
    port: 10001
    targetPort: 10001
#  type: NodePort
  type: LoadBalancer


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-sample-deployment
  namespace: demo
  labels:
    app: springboot-sample
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: springboot-sample
  template:
    metadata:
      labels:
        app: springboot-sample
    spec:
      containers:
      - name: springboot-sample
        image: devops-tools.pmsplus.co.kr:9500/springboot-sample:1.00
        args: ["--spring.profiles.active=test"]
        ports:
        - containerPort: 10001
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
      imagePullSecrets:
      - name: regcred
  strategy:
    type: RollingUpdate
